user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  aaa:
    username: william
    password: william

url: http://www.tcpjwtester.top

mysql:
    db: test_mysql
    host: 190.168.2.191
    password: 123456
    port: 3306
    user: root